/** @type {import('tailwindcss').Config} */

// Every colour is a CSS variable (src/app/theme-colors.css, generated by scripts/gen-theme.mjs),
// in three roles so `html.dark` can restyle the whole app without per-class `dark:` variants:
// backgrounds (--b-*), text (--t-*) and lines (--l-*). See the script for the dark mapping.
const STEPS = ['50', '100', '200', '300', '400', '500', '600', '700', '800', '900', '950'];
const FAMILIES = [
  'slate', 'gray', 'zinc', 'neutral', 'stone', 'red', 'orange', 'amber', 'yellow', 'lime', 'green', 'emerald', 'teal', 'cyan',
  'sky', 'blue', 'indigo', 'violet', 'purple', 'fuchsia', 'pink', 'rose',
];

function palette(role) {
  const v = name => `rgb(var(--${role}-${name}) / <alpha-value>)`;
  const out = { transparent: 'transparent', current: 'currentColor', inherit: 'inherit', white: v('white'), black: v('black') };
  for (const f of FAMILIES) out[f] = Object.fromEntries(STEPS.map(s => [s, v(`${f}-${s}`)]));
  return out;
}

const bg = palette('b');
const text = palette('t');
const line = palette('l');

module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    colors: bg,
    textColor: text,
    placeholderColor: text,
    borderColor: { ...line, DEFAULT: line.slate['200'] },
    divideColor: { ...line, DEFAULT: line.slate['200'] },
    ringColor: { ...line, DEFAULT: line.blue['500'] },
    outlineColor: line,
    ringOffsetColor: bg,
    extend: {
      fontFamily: {
        sans: ['system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
      },
      boxShadow: {
        'card': '0 1px 3px rgba(0, 0, 0, 0.1)',
        'card-hover': '0 4px 6px rgba(0, 0, 0, 0.1)',
      },
      borderRadius: {
        'card': '0.75rem',
      },
    },
  },
  plugins: [],
}
