// Generates src/app/theme-colors.css: every Tailwind colour as a CSS variable, light and dark.
//
// Each family gets three roles, so one class name works in both themes:
//   --b-<family>-<step>  backgrounds, gradients, fills, shadows (bg-*, from-*, fill-*)
//   --t-<family>-<step>  text and placeholders (text-*)
//   --l-<family>-<step>  borders, rings, dividers, outlines (border-*, ring-*, divide-*)
// Light = the stock Tailwind palette. Dark: surfaces go dark (white = card, 50 = page),
// neutral text goes light, tinted backgrounds (50-300) become dark tints of the hue, and
// coloured text moves to its light steps; solid fills (500-700) keep their hue so white
// text on buttons and badges stays readable.
//
// Run: node scripts/gen-theme.mjs   (then commit the CSS)
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';

const require = createRequire(import.meta.url);
const colors = require('tailwindcss/colors');

const STEPS = ['50', '100', '200', '300', '400', '500', '600', '700', '800', '900', '950'];
const NEUTRALS = ['slate', 'gray', 'zinc', 'neutral', 'stone'];
const HUES = ['red', 'orange', 'amber', 'yellow', 'lime', 'green', 'emerald', 'teal', 'cyan', 'sky', 'blue', 'indigo', 'violet', 'purple', 'fuchsia', 'pink', 'rose'];
const SURFACE = '#0f172a';

const rgb = hex => {
  const h = hex.replace('#', '');
  return [0, 2, 4].map(i => parseInt(h.slice(i, i + 2), 16));
};
const triplet = c => (Array.isArray(c) ? c : rgb(c)).map(Math.round).join(' ');
const mix = (a, b, w) => rgb(a).map((v, i) => v * w + rgb(b)[i] * (1 - w));

// neutral roles in the dark theme (slate based, used for every grey family)
const DARK_NEUTRAL = {
  b: { white: '#0f172a', 50: '#0b1120', 100: '#1e293b', 200: '#334155', 300: '#475569', 400: '#64748b', 500: '#64748b', 600: '#475569', 700: '#334155', 800: '#334155', 900: '#475569', 950: '#334155' },
  t: { white: '#ffffff', 50: '#f8fafc', 100: '#e2e8f0', 200: '#64748b', 300: '#5b6b82', 400: '#7c8ba1', 500: '#94a3b8', 600: '#b4c0d0', 700: '#cbd5e1', 800: '#e2e8f0', 900: '#f1f5f9', 950: '#f8fafc' },
  l: { white: '#0f172a', 50: '#1e293b', 100: '#1e293b', 200: '#2b3a52', 300: '#3b4a63', 400: '#55657d', 500: '#64748b', 600: '#7c8ba1', 700: '#94a3b8', 800: '#cbd5e1', 900: '#e2e8f0', 950: '#f1f5f9' },
};

function darkHue(p) {
  return {
    b: { 50: mix(p[500], SURFACE, 0.12), 100: mix(p[500], SURFACE, 0.2), 200: mix(p[500], SURFACE, 0.3), 300: mix(p[500], SURFACE, 0.45),
      400: p[400], 500: p[500], 600: p[600], 700: p[600], 800: p[700], 900: p[800], 950: p[900] },
    t: { 50: p[50], 100: p[100], 200: p[200], 300: p[300], 400: p[300], 500: p[400], 600: p[400], 700: p[300], 800: p[200], 900: p[100], 950: p[50] },
    l: { 50: mix(p[500], SURFACE, 0.18), 100: mix(p[500], SURFACE, 0.25), 200: mix(p[500], SURFACE, 0.35), 300: mix(p[500], SURFACE, 0.5),
      400: p[500], 500: p[500], 600: p[500], 700: p[400], 800: p[300], 900: p[200], 950: p[100] },
  };
}

const light = [];
const dark = [];
for (const role of ['b', 't', 'l']) {
  light.push(`  --${role}-white: 255 255 255;`, `  --${role}-black: 0 0 0;`);
  dark.push(`  --${role}-white: ${triplet(DARK_NEUTRAL[role].white)};`, `  --${role}-black: ${role === 't' ? '241 245 249' : '0 0 0'};`);
}
for (const fam of [...NEUTRALS, ...HUES]) {
  const p = colors[fam];
  const d = NEUTRALS.includes(fam) ? DARK_NEUTRAL : darkHue(p);
  for (const role of ['b', 't', 'l']) {
    for (const s of STEPS) {
      light.push(`  --${role}-${fam}-${s}: ${triplet(p[s])};`);
      dark.push(`  --${role}-${fam}-${s}: ${triplet(d[role][s])};`);
    }
  }
}

const css = `/* Generated by scripts/gen-theme.mjs: Tailwind colours as variables, light and dark. Do not edit. */
:root {
${light.join('\n')}
}

html.dark {
  color-scheme: dark;
${dark.join('\n')}
}
`;
writeFileSync(new URL('../src/app/theme-colors.css', import.meta.url), css);
console.log(`theme-colors.css: ${light.length} variables per theme`);
